# Sistemas Inteligentes 2021/2022

## Mini-projeto 3: Aprendizagem Automática

## Relatório


## Grupo: 02

Número: 55852 - Nome: Marcos Leitão

Número: 56909 - Nome: Miguel Fernandes


## 1. Processamento dos dados

Usaremos a biblioteca pandas para a leitura do ficheiro csv train e apresentação de dados.

<b>Matriz de dados</b>

In [2]:
import pandas as pd

df_cj = pd.read_csv("train.csv", sep=',')

df_cj

ID  N_Days Status             Drug    Age Sex  Ascites Hepatomegaly  \
0      0    2644      C  D-penicillamine  20296   F        N            N   
1      1    3492      C          Unknown  21915   F  Unknown      Unknown   
2      2    1702      C  D-penicillamine  18806   F        N            N   
3      3    3523      C          Unknown  14610   F  Unknown      Unknown   
4      4    3428      D          Placebo  13727   F        N            Y   
..   ...     ...    ...              ...    ...  ..      ...          ...   
324  324    2255      C  D-penicillamine  22642   F        N            N   
325  325    1899      C          Unknown  14975   M  Unknown      Unknown   
326  326    1152      D  D-penicillamine  25546   M        N            Y   
327  327      71      D  D-penicillamine  18972   F        N            Y   
328  328    1874      C          Placebo  24257   F        N            N   

     Spiders Edema  Bilirubin  Cholesterol  Albumin      Copper     Alk_Phos  \
0          N     N        0.5   369.510563     3.85   63.000000   663.000000   
1    Unknown     N        0.6   369.510563     4.38   97.648387  1982.655769   
2          N     N        1.1   414.000000     3.44   80.000000  1003.000000   
3    Unknown     N        0.6   369.510563     4.04   97.648387  1982.655769   
4          Y     Y        3.3   299.000000     3.55  131.000000  1029.000000   
..       ...   ...        ...          ...      ...         ...          ...   
324        N     N        0.6   213.000000     4.07   12.000000  5300.000000   
325  Unknown     N        1.7   369.510563     3.66   97.648387  1982.655769   
326        N     N        2.3   586.000000     3.01  243.000000  2276.000000   
327        Y     S       12.2   394.000000     3.08  111.000000  2132.000000   
328        N     S        0.6   280.000000     3.35   97.648387  1093.000000   

           SGOT  Tryglicerides  Platelets  Prothrombin  Stage  
0     79.050000     124.702128      311.0          9.7    1.0  
1    122.556346     124.702128      269.0         10.6    2.0  
2     99.000000      55.000000      271.0          9.6    1.0  
3    122.556346     124.702128      130.0         11.2    2.0  
4    119.350000      50.000000      199.0         11.7    3.0  
..          ...            ...        ...          ...    ...  
324   57.350000      68.000000      240.0         11.0    1.0  
325  122.556346     124.702128       92.0         11.0    4.0  
326  114.700000     126.000000      339.0         10.9    3.0  
327  155.000000     243.000000      165.0         11.6    4.0  
328  128.650000      81.000000      295.0          9.8    2.0  

[329 rows x 20 columns]

<b style='color: red'> Nota !! </b> <br>
Antes de passarmos para o próximo passo temos que separar as variáveis dependentes das independentes e usar apenas as colunas relevantes dentro do dataset. <br>
Vamos também extrair os nomes das colunas, pois serão úteis no futuro para interpretar os resultados e modelos construídos

In [3]:
import numpy as np

col_indexs = [i for i in range(1,df_cj.shape[1]-1)] #indices das colunas relevantes
col_names = np.array(df_cj.columns)[col_indexs] #nomes das colunas relevantes

print('Nome das colunas relevantes e indepentes: ')
print(col_names)
print()

print('Valor das colunas relevantes e indepentes: ')
indpValues = df_cj.values[:,col_indexs] 
print(indpValues)
print()

print('Nome das colunas relevantes e dependentes: ')
print(np.array(df_cj.columns)[df_cj.shape[1]-1])
print()

print('Valor das colunas relevantes e dependentes: ')
deptValues = df_cj.values[:,19] 
print(deptValues)

Nome das colunas relevantes e indepentes: 
['N_Days' 'Status' 'Drug' 'Age' 'Sex' 'Ascites' 'Hepatomegaly' 'Spiders'
 'Edema' 'Bilirubin' 'Cholesterol' 'Albumin' 'Copper' 'Alk_Phos' 'SGOT'
 'Tryglicerides' 'Platelets' 'Prothrombin']

Valor das colunas relevantes e indepentes: 
[[2644 'C' 'D-penicillamine' ... 124.70212765957449 311.0 9.7]
 [3492 'C' 'Unknown' ... 124.70212765957449 269.0 10.6]
 [1702 'C' 'D-penicillamine' ... 55.0 271.0 9.6]
 ...
 [1152 'D' 'D-penicillamine' ... 126.0 339.0 10.9]
 [71 'D' 'D-penicillamine' ... 243.0 165.0 11.6]
 [1874 'C' 'Placebo' ... 81.0 295.0 9.8]]

Nome das colunas relevantes e dependentes: 
Stage

Valor das colunas relevantes e dependentes: 
[1.0 2.0 1.0 2.0 3.0 4.0 3.0 4.0 4.0 4.0 4.0 1.0 1.0 3.0 3.0 1.0 3.0 4.0
 4.0 4.0 1.0 2.0 2.0 2.0 3.0 2.0 4.0 4.0 4.0 4.0 3.0 1.0 4.0 4.0 3.0 3.0
 4.0 3.0 3.0 2.0 4.0 3.0 2.0 2.0 3.0 3.0 4.0 3.0 3.0 2.0 4.0 4.0 2.0 2.0
 2.0 3.0 4.0 1.0 4.0 1.0 3.0 2.0 2.0 3.0 3.0 4.0 4.0 4.0 3.0 3.0 3.0 4.0
 3.0 3.0 3.0 2.0 2.

## 2. Ajustamento dos modelos
### 2.1. Validar um modelo usando conjunto de treino e teste
Para validar o modelo vamos fornecer novos dados (que não foram vistos pelo modelo) para os quais temos classes.

<b style= 'color: red' >Nota!!</b> <br>
Os classificadores do scikit-learn, não podem usar dados categóricos na matriz de dados, pelo que estes terão que ser binarizados, ou seja cada valor possível de uma variável é transformado numa coluna que pode ter valores 1 ou 0, consoante esse valor ocorra ou não.

In [4]:
# primeiro construir um dataframe para a matriz X
df_cjX = df_cj[col_names]

# criar um novo DataFrame
df_cjXdum = pd.get_dummies(df_cjX, columns = col_names)

df_cjXdum 

print()

Xdum=df_cjXdum.values

Vamos então dividir o nosso conjunto de dados
- o conjunto de treino (x_train)
- o conjunto de teste (x_test)
- dados e as classes de treino (y_train)
- dados e as classes de teste (y_test)

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

Vamos aplicar dois testes. <br>
Para uma primeira interação, vamos dividir o nosso conjunto de dados em 0.25 teste e 0.75 treino. <br>
Para um segunda interação, iremos descobrir qual o melhor modelo.

<b> 0.25 teste e 0.75 treino </b>

#### 2.1.1 Árvores de Decisão

In [6]:
x_train, x_test, y_train, y_test = train_test_split(Xdum,list(deptValues),test_size=0.25,train_size=0.75)

Treinar uma árvore de decisão usando apenas o conjunto de treino

In [7]:
sk_cj = DecisionTreeClassifier(criterion='entropy')
sk_cj.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

<b> Accuracy </b> <br>
Podemos agora fazer previsões usando o conjunto de teste e comparar essas previsões com as classes verdadeiras (y_test), obtendo assim a exatidão (accuracy) do nosso modelo.

In [8]:
sk_cj.score(x_test, y_test)

0.42168674698795183

<b> Cross-validation </b> <br>
Para avaliarmos o desempenho do nosso modelo iremos recorrer a uma técnica mais robusta, designada por validação cruzada, cross-validation, que consiste numa simples divisão do conjunto de dados em dois sub-conjuntos, um de treino e um de teste. 

In [9]:
from sklearn.model_selection import cross_val_score

sk_cj = DecisionTreeClassifier(criterion='entropy')

scores = cross_val_score(sk_cj,X=Xdum,y=list(deptValues),cv=10)

print('CV accuracy:', *scores, sep='\n\t')

print('Average CV accuracy: %.3f +/- %.3f' %(np.mean(scores), np.std(scores)))

CV accuracy:
	0.42424242424242425
	0.48484848484848486
	0.3333333333333333
	0.36363636363636365
	0.3939393939393939
	0.5151515151515151
	0.36363636363636365
	0.3939393939393939
	0.30303030303030304
	0.3125
Average CV accuracy: 0.389 +/- 0.066


#### 2.1.2 K vizinhos mais próximos 
O algoritmo encontra os vizinhos mais próximos no conjunto de treino <br>
Vamos então aplicar o k-NN aos dados, começando com 1 vizinho mais próximo valide o modelo calculando a exatidão nos conjuntos de treino e de teste.
Relembrando que a divisão é feita em 0.25 teste e 0.75 treino

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

knn_cj = KNeighborsClassifier(n_neighbors=1)

x_train, x_test, y_train, y_test = train_test_split(Xdum,list(deptValues),test_size=0.25,train_size=0.75)


Treinar usando apenas o conjunto de treino

In [11]:
knn_cj.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

<b> Accuracy </b>

In [12]:
knn_cj.score(x_test, y_test)

0.3493975903614458

<b> Cross-validation </b>

In [13]:
scores = cross_val_score(knn_cj,X=Xdum,y=list(deptValues),cv=10)

print('CV accuracy:', *scores, sep='\n\t')

print('Average CV accuracy: %.3f +/- %.3f' %(np.mean(scores), np.std(scores)))

CV accuracy:
	0.24242424242424243
	0.30303030303030304
	0.2727272727272727
	0.42424242424242425
	0.18181818181818182
	0.30303030303030304
	0.3333333333333333
	0.21212121212121213
	0.42424242424242425
	0.28125
Average CV accuracy: 0.298 +/- 0.076


#### 2.1.3 Naive Bayes
Naive Bayes são uma familia de classificadores probabilisticos baseados no teorema de Bayes e com uma forte suposição de independência entre os atributos. <br>
O modelo é chamado de "naive" porque não se espera que os atributos sejam independentes, mesmo condicionados pela classe.

In [14]:
x_train, x_test, y_train, y_test = train_test_split(Xdum,list(deptValues),test_size=0.25,train_size=0.75)

from sklearn.naive_bayes import GaussianNB

nb_cj = GaussianNB()

nb_cj.fit(x_train, y_train)

GaussianNB()

<b> Accuracy </b> <br>

In [15]:
nb_cj.score(x_test, y_test)

0.3373493975903614

<b> Cross-validation </b> 

In [16]:
scores = cross_val_score(nb_cj,X=Xdum,y=list(deptValues),cv=10)

print('CV accuracy:', *scores, sep='\n\t')

print('Average CV accuracy: %.3f +/- %.3f' %(np.mean(scores), np.std(scores)))

CV accuracy:
	0.3333333333333333
	0.2727272727272727
	0.3333333333333333
	0.36363636363636365
	0.30303030303030304
	0.3333333333333333
	0.2727272727272727
	0.30303030303030304
	0.42424242424242425
	0.28125
Average CV accuracy: 0.322 +/- 0.045


### 2.2. Seleção e apresentação do melhor modelo
Relembrando: 

- <b> Xdum </b> : corresponde aos valores do novo dataframe binarizado
- <b> deptValues </b>: corresponde aos aos valores dependentes de cada linha

Para selecionar o melhor modelo, vamos fazer uma função que para um determinado modelo testa a Árvores de Decisão, Naive Bayes e K-vizinhos ( seleciona o k que tiver maior accuracy e cross-validation). <br>

In [17]:
def best(test_size=0.5,train_size=0.5,data=Xdum,dependent=list(deptValues)):

    x_train_final= ''
    x_test_final = ''
    y_train_final = ''
    y_test_final = ''

    accuracy_tree = 0
    cross_tree = 0

    accuracy_kv = 0
    cross_kv = 0

    accuracy_b = 0
    cross_b = 0
    i = 0

    x_train, x_test, y_train, y_test = train_test_split(data,dependent,test_size=test_size,train_size=train_size,random_state=2)

    #Árvores de Decisão
    sk_cj = DecisionTreeClassifier(criterion='entropy',random_state=2)
    sk_cj.fit(x_train,y_train)
    accuracy_tree_test = sk_cj.score(x_test, y_test)

    scores = cross_val_score(sk_cj,X=Xdum,y=list(deptValues),cv=10) 
    cross_tree_test = np.mean(scores) 

    accuracy_tree = accuracy_tree_test
    cross_tree = cross_tree_test

    #Naive Bayes
    nb_cj = GaussianNB()
    nb_cj.fit(x_train, y_train)
    accuracy_b_test = nb_cj.score(x_test, y_test)

    scores = cross_val_score(nb_cj,X=Xdum,y=list(deptValues),cv=10)
    cross_b_test = np.mean(scores)

    accuracy_b = accuracy_b_test
    cross_b = cross_b_test

    #K vizinhos mais próximos
    for k in range(1,165):

        knn_cj = KNeighborsClassifier(n_neighbors=k)        
        knn_cj.fit(x_train, y_train)
        accuracy_kv_test = knn_cj.score(x_test, y_test)

        scores = cross_val_score(knn_cj,X=Xdum,y=list(deptValues),cv=10)
        cross_kv_test = np.mean(scores)


        if accuracy_kv_test > accuracy_kv and cross_kv_test> cross_kv:

            i = k
            accuracy_kv = accuracy_kv_test
            cross_kv = cross_kv_test


    x_train_final = x_train
    x_test_final = x_test 
    y_train_final = y_train
    y_test_final = y_test

    return (x_train_final,y_train_final,x_test_final,y_test_final,accuracy_tree,cross_tree,accuracy_kv,cross_kv,i,accuracy_b,cross_b)

Vamos testar vários modelos coloca-los numa tabela e escolher o melhor.
Com as seguintes colunas:

- test_size	
- train_size	
- ArvoreTestes_accuracy	
- ArvoreTestes_cross	
- Kvizinhos_accuracy	
- Kvizinhos__cross	
- Kvizinhos_k	
- Nbayes_accuracy	
- Nbayes_accuracy_cross

<b> <span style='color: red'> Nota !!! </span> </b> <br>
A execução do código abaixo, implica um tempo esperado até obter os resultados de aproximadante 8 minutos, dependendo do processador, para resultados mais rápido aumentar o delta <b> default = 0.01 </b>. <br>
<span style='color: red'> Ao aumentar o delta obtem-se menos informação.</span> <br>

In [18]:
test_size=0.5
train_size=0.5

columns = ['test_size','train_size','ArvoreTestes_accuracy','ArvoreTestes_cross','Kvizinhos_accuracy',
                                    'Kvizinhos__cross','Kvizinhos_k','Nbayes_accuracy','Nbayes_accuracy_cross']
data = []
count = 0
while(test_size >= 0.01):

    melhor = best(round(test_size,2),round(train_size,2))
    
    data += [[round(test_size,2),round(train_size,2),melhor[4],melhor[5],melhor[6],melhor[7],
            melhor[8],melhor[9],melhor[10]]]
    
    test_size -= 0.01
    train_size +=0.01

df_modelo = pd.DataFrame(data, columns = columns)

df_modelo
      

test_size  train_size  ArvoreTestes_accuracy  ArvoreTestes_cross  \
0        0.50        0.50               0.339394            0.416098   
1        0.49        0.51               0.382716            0.416098   
2        0.48        0.52               0.341772            0.416098   
3        0.47        0.53               0.361290            0.416098   
4        0.46        0.54               0.348684            0.416098   
5        0.45        0.55               0.302013            0.416098   
6        0.44        0.56               0.400000            0.416098   
7        0.43        0.57               0.330986            0.416098   
8        0.42        0.58               0.316547            0.416098   
9        0.41        0.59               0.385185            0.416098   
10       0.40        0.60               0.378788            0.416098   
11       0.39        0.61               0.379845            0.416098   
12       0.38        0.62               0.333333            0.416098   
13       0.37        0.63               0.385246            0.416098   
14       0.36        0.64               0.411765            0.416098   
15       0.35        0.65               0.353448            0.416098   
16       0.34        0.66               0.401786            0.416098   
17       0.33        0.67               0.348624            0.416098   
18       0.32        0.68               0.377358            0.416098   
19       0.31        0.69               0.372549            0.416098   
20       0.30        0.70               0.333333            0.416098   
21       0.29        0.71               0.322917            0.416098   
22       0.28        0.72               0.311828            0.416098   
23       0.27        0.73               0.348315            0.416098   
24       0.26        0.74               0.313953            0.416098   
25       0.25        0.75               0.397590            0.416098   
26       0.24        0.76               0.367089            0.416098   
27       0.23        0.77               0.394737            0.416098   
28       0.22        0.78               0.383562            0.416098   
29       0.21        0.79               0.357143            0.416098   
30       0.20        0.80               0.378788            0.416098   
31       0.19        0.81               0.476190            0.416098   
32       0.18        0.82               0.366667            0.416098   
33       0.17        0.83               0.375000            0.416098   
34       0.16        0.84               0.396226            0.416098   
35       0.15        0.85               0.360000            0.416098   
36       0.14        0.86               0.382979            0.416098   
37       0.13        0.87               0.372093            0.416098   
38       0.12        0.88               0.300000            0.416098   
39       0.11        0.89               0.351351            0.416098   
40       0.10        0.90               0.333333            0.416098   
41       0.09        0.91               0.366667            0.416098   
42       0.08        0.92               0.333333            0.416098   
43       0.07        0.93               0.333333            0.416098   
44       0.06        0.94               0.250000            0.416098   
45       0.05        0.95               0.294118            0.416098   
46       0.04        0.96               0.357143            0.416098   
47       0.03        0.97               0.400000            0.416098   
48       0.02        0.98               0.428571            0.416098   

    Kvizinhos_accuracy  Kvizinhos__cross  Kvizinhos_k  Nbayes_accuracy  \
0             0.484848          0.477178          110         0.339394   
1             0.506173          0.483333          127         0.345679   
2             0.506329          0.465057          114         0.354430   
3             0.477419          0.467898           95         0.348387   
4             0.473684          0

Faltou-nos testar para o caso de test_size = 0.01 e train_size = 0.99
Vamos testar

In [19]:
melhor = best(0.01, 0.99)

print('Arvore Testes')
print('accuracy',melhor[4])
print('cross',melhor[5])
print()

print('K vizinhos')
print('accuracy',melhor[6])
print('cross',melhor[7])
print('k',melhor[8])
print()

print('N bayes')
print('accuracy',melhor[9])
print('cross',melhor[10])

Arvore Testes
accuracy 0.75
cross 0.4160984848484848

K vizinhos
accuracy 0.75
cross 0.4011363636363637
k 4

N bayes
accuracy 0.5
cross 0.3220643939393939


Pela informação disponibilizada pela tabela e pelo ultimo teste, chegamos a conclusão que o melhor modelo a partida será: <br>
- test_size = 0.01 e train_size = 0.99

In [20]:
melhor = best(0.01, 0.99)

print('Conjunto de Treino')
print(melhor[0])
print()

print('Conjunto de Teste')
print(melhor[2])
print()

Conjunto de Treino
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Conjunto de Teste
[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]



## 3. Validação do modelo final ajustado com um conjunto de validação independente
Mediante a nossa escolha anterior, agora testar o desempenho sobre `test.csv`.

* Preparação do data set

In [21]:
df_cjT = pd.read_csv("test.csv", sep=',')

x = list(df_cjX[col_names].values) #conjunto treino
y = list(df_cjT[col_names].values) #conjunto teste

data = x + y 

df = pd.DataFrame(data, columns = col_names)

df_Final = pd.get_dummies(df, columns = col_names)

col_names_dum=np.array(df_Final.columns)

XdumFinal= df_Final.values #valores dos conjuntos concatenados

df_Final

N_Days_41  N_Days_43  N_Days_51  N_Days_71  N_Days_77  N_Days_94  \
0            0          0          0          0          0          0   
1            0          0          0          0          0          0   
2            0          0          0          0          0          0   
3            0          0          0          0          0          0   
4            0          0          0          0          0          0   
..         ...        ...        ...        ...        ...        ...   
407          0          0          0          0          0          0   
408          0          0          0          0          0          0   
409          0          0          0          0          0          0   
410          0          0          0          0          0          0   
411          0          0          0          0          0          0   

     N_Days_110  N_Days_111  N_Days_130  N_Days_131  ...  Prothrombin_13.0  \
0             0           0           0           0  ...                 0   
1             0           0           0           0  ...                 0   
2             0           0           0           0  ...                 0   
3             0           0           0           0  ...                 0   
4             0           0           0           0  ...                 0   
..          ...         ...         ...         ...  ...               ...   
407           0           0           0           0  ...                 0   
408           0           0           0           0  ...                 0   
409           0           0           0           0  ...                 0   
410           0           0           0           0  ...                 0   
411           0           0           0           0  ...                 0   

     Prothrombin_13.1  Prothrombin_13.2  Prothrombin_13.3  Prothrombin_13.6  \
0                   0                 0                 0                 0   
1                   0                 0                 0                 0   
2                   0                 0                 0                 0   
3                   0                 0                 0                 0   
4                   0                 0                 0                 0   
..                ...               ...               ...               ...   
407                 0                 0                 0                 0   
408                 0                 0                 0                 0   
409                 0                 0                 0                 0   
410                 0                 0                 0                 0   
411                 0                 0                 0                 0   

     Prothrombin_13.8  Prothrombin_14.1  Prothrombin_15.2  Prothrombin_17.1  \
0                   0                 0                 0                 0   
1                   0                 0                 0                 0   
2                   0                 0                 0                 0   
3                   0                 0                 0                 0   
4                   0                 0                 0                 0   
..                ...               ...               ...               ...   
407                 0                 0                 0                 0   
408                 0                 0                 0                 0   
409                 0                 0                 0                 0   
410                 0                 0                 0                 0   
411                 0                 0                 0                 0   

     Prothrombin_18.0  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  
..                ...  
407                 0  
408                 0  
409                 0  
410                 0  
411                 0  

[412

Vamos verificar o desempenho .

In [22]:
melhor = best(0.01, 0.99,XdumFinal[:len(x)],list(deptValues))

print('Conjunto de Treino')
print(melhor[0])
print()

print('Conjunto de Teste')
print(melhor[2])
print()

print('Arvore Testes')
print('accuracy',melhor[4])
print('cross',melhor[5])
print()

print('K vizinhos')
print('accuracy',melhor[6])
print('cross',melhor[7])
print('k',melhor[8])
print()

print('N bayes')
print('accuracy',melhor[9])
print('cross',melhor[10])
print()

Conjunto de Treino
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Conjunto de Teste
[[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Arvore Testes
accuracy 0.75
cross 0.4160984848484848

K vizinhos
accuracy 0.75
cross 0.4011363636363637
k 4

N bayes
accuracy 0.5
cross 0.3220643939393939



## 4. Competição

Relembrando:

- x: lista do #conjunto treino
- XdumFinal: #valores dos conjuntos concatenados 
- deptValues: valores dependentes

In [23]:
knn_cj = KNeighborsClassifier(n_neighbors=4)        
knn_cj.fit(XdumFinal[:len(x)], list(deptValues))

count=len(x)
print('ID,Stage')
for i in XdumFinal[len(x):]:
    p = knn_cj.predict([i])
    print(str(count)+','+str(int(p[0])))
    count +=1
        


ID,Stage
329,3
330,3
331,1
332,3
333,3
334,3
335,2
336,4
337,4
338,4
339,4
340,3
341,3
342,3
343,4
344,3
345,3
346,3
347,1
348,4
349,3
350,4
351,4
352,2
353,4
354,3
355,4
356,3
357,3
358,2
359,3
360,3
361,1
362,3
363,2
364,3
365,3
366,3
367,3
368,4
369,4
370,4
371,3
372,4
373,3
374,2
375,3
376,3
377,4
378,3
379,2
380,2
381,3
382,2
383,3
384,4
385,2
386,3
387,4
388,3
389,3
390,2
391,3
392,2
393,4
394,3
395,3
396,2
397,2
398,4
399,3
400,3
401,3
402,3
403,3
404,3
405,3
406,4
407,4
408,3
409,4
410,2
411,3
